### ISSUE TITLE
Question: Could it be better to not compress the blobs ?

### ISSUE THREAD

**Issue by fungiboletus** [ysimonson/binlog#43] opened 2023-11-21 18:52 UTC
Hi,

I came across your project as I was considering to implement something to dump sensor data coming from a stream into a sqlite database.

I see that you compress every message if they are greater or equal than 32, but I feel like it may be better to not compress per message.

Someone else made some tests about this:
https://github.com/phiresky/sqlite-zstd

![](https://github.com/phiresky/sqlite-zstd/raw/master/doc/2022-07-31-19-27-57.png)

Compressing the whole database file has downsides, but it may be better for archiving purposes.

Also, I browsed the code and it looks like every non empty blob is decompressed. Does the zstd decompressor accepts non compressed blobs and returns them, or is it a bug?

**Comment by ysimonson** [comment] 2023-11-23 14:14
> Compressing the whole database file has downsides, but it may be better for archiving purposes.

Compressing the whole database will indeed be the best for archival purposes, but isn't good for streaming since you'd decompress and recompress the whole database for every insert.

> https://github.com/phiresky/sqlite-zstd

`sqlite-zstd` looks really useful. I can't recall if I had seen/explored this when making binlog, but I probably would've ruled it out since stability and lack of data loss were of the utmost importance, so I only wanted to rely on libraries when they were fairly battle-tested. There's also [zipvfs](https://www.sqlite.org/zipvfs/doc/trunk/www/readme.wiki), though it's closed source.

> Does the zstd decompressor accepts non compressed blobs and returns them, or is it a bug?

zstd decompressor indeed accepts non-compressed blobs. The unit and fuzz tests validate this.

**Comment by earlyraven** [comment] 2023-12-21 06:52
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Closed as completed** 2023-12-21 11:25 UTC

**Comment by fungiboletus** [comment] 2023-12-21 21:18
Thanks a lot for your answer. I missed the notification last time.
